_core:
  default_config_hash: ByOVf1cU9r5NkZ4ieBJ7k9sUid6jb03ojMN1gjJ0-OU
site_key: 6Lec8sAsAAAAAKB26spUiq8NRpGc_eyJxkyNCOLL
secret_key: 6Lec8sAsAAAAACK-IykGhLPiGg0wabpDQc3dzeNf
verify_hostname: true
use_globally: false
widget:
  theme: light
  type: image
  size: ''
  noscript: false
